name: "Release debug/test stuff"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
jobs:
  build:
    name: "Create Release"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        poetry-version: ["latest"]
        os: [ubuntu-24.04]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Poetry build
        run: poetry build
      - id: numeric-version
        name: Remove v from version
        run: echo "ver=`${{ github.ref }} | sed 's/^v//'`" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.numeric-version.outputs.ver }}
          release_name: Release ${{ steps.numeric-version.outputs.ver }}
          body: |
            Changes in this Release
            - TODO pull from some file automatically
          draft: true
          prerelease: false
